<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php';redirect_if_not_logged_in();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$stmt=db()->prepare('SELECT mr.*,CONCAT(c.first_name," ",c.last_name) AS client_name FROM mutual_requests mr JOIN dossiers d ON d.id=mr.dossier_id JOIN clients c ON c.id=d.client_id WHERE mr.id=?');$stmt->execute([$id]);$request=$stmt->fetch();if(!$request){http_response_code(404);exit('Demande introuvable.');}
$portals=db()->query('SELECT *,COALESCE(url,portal_url) AS active_url FROM mutual_portals WHERE is_active=1 ORDER BY name')->fetchAll();$docStmt=db()->prepare('SELECT id,original_file_name,original_name,document_type FROM documents WHERE dossier_id=? AND deleted_at IS NULL ORDER BY created_at DESC');$docStmt->execute([$request['dossier_id']]);$documents=$docStmt->fetchAll();$pageTitle='Demande mutuelle '.dossier_number((int)$request['dossier_id']);require dirname(__DIR__) . '/includes/header.php';
?>
<section class="page-actions"><div class="copy"><h2><?= e($request['client_name']) ?></h2><p>Checklist locale et suivi manuel de la prise en charge.</p></div><a class="btn btn-outline" href="<?= e(app_url('pages/documents.php?dossier_id='.$request['dossier_id'])) ?>">Documents du dossier</a></section>
<form class="card" method="post" action="<?= e(app_url('actions/mutual_request_save.php')) ?>" data-unsaved-warning><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$request['id'] ?>"><input type="hidden" name="dossier_id" value="<?= (int)$request['dossier_id'] ?>">
<section class="form-section"><h3>Organisme et suivi</h3><div class="form-grid form-grid-3"><label class="field"><span>Portail</span><select name="portal_id"><option value="">—</option><?php foreach($portals as $portal):?><option value="<?= (int)$portal['id'] ?>" <?= $request['portal_id']==$portal['id']?'selected':'' ?>><?= e($portal['name']) ?></option><?php endforeach;?></select></label><label class="field"><span>Statut</span><select name="status"><?php foreach(['a_preparer','envoyee','en_attente','acceptee','partielle','refusee','expiree','annulee'] as $status):?><option value="<?= e($status) ?>" <?= $request['status']===$status?'selected':'' ?>><?= e(status_label($status)) ?></option><?php endforeach;?></select></label><label class="field"><span>Référence PEC</span><input name="reference" value="<?= e($request['reference']?:$request['external_reference']??'') ?>"></label><label class="field"><span>Part RO</span><input type="number" min="0" step=".01" name="ro_amount" value="<?= e((string)$request['ro_amount']) ?>"></label><label class="field"><span>Part RC</span><input type="number" min="0" step=".01" name="rc_amount" value="<?= e((string)$request['rc_amount']) ?>"></label><label class="field"><span>RAC</span><input type="number" min="0" step=".01" name="rac_amount" value="<?= e((string)$request['rac_amount']) ?>"></label><label class="field"><span>Montant accepté</span><input type="number" min="0" step=".01" name="accepted_amount" value="<?= e((string)($request['accepted_amount']?:$request['approved_amount'])) ?>"></label><label class="field"><span>Envoyée le</span><input type="datetime-local" name="sent_at" value="<?= e($request['sent_at']?date('Y-m-d\TH:i',strtotime($request['sent_at'])):'') ?>"></label><label class="field"><span>Réponse attendue</span><input type="datetime-local" name="response_due_at" value="<?= e($request['response_due_at']?date('Y-m-d\TH:i',strtotime($request['response_due_at'])):'') ?>"></label><label class="field"><span>Réponse reçue le</span><input type="datetime-local" name="response_at" value="<?= e(($request['response_at']?:$request['response_received_at'])?date('Y-m-d\TH:i',strtotime($request['response_at']?:$request['response_received_at'])):'') ?>"></label><label class="field"><span>Valide jusqu’au</span><input type="date" name="valid_until" value="<?= e($request['valid_until']??'') ?>"></label><label class="field"><span>Justificatif lié</span><select name="document_id"><option value="">—</option><?php foreach($documents as $document):?><option value="<?= (int)$document['id'] ?>" <?= $request['document_id']==$document['id']?'selected':'' ?>><?= e($document['original_file_name']?:$document['original_name']) ?></option><?php endforeach;?></select></label><label class="field field-full"><span>Motif de refus</span><input name="refusal_reason" value="<?= e($request['refusal_reason']??'') ?>"></label></div></section>
<section class="form-section"><h3>Pièces vérifiées</h3><div class="form-grid"><?php foreach(['has_identity'=>'Identité','has_prescription'=>'Ordonnance','has_rights_certificate'=>'Attestation de droits','has_quote'=>'Devis'] as $field=>$label):?><label class="check-row"><input type="checkbox" name="<?= e($field) ?>" value="1" <?= $request[$field]?'checked':'' ?>><span><?= e($label) ?></span></label><?php endforeach;?></div></section>
<label class="field"><span>Notes internes (jamais de mot de passe)</span><textarea name="comment"><?= e($request['comment']?:$request['notes']??'') ?></textarea></label>
<div class="form-footer"><a class="btn btn-outline" href="<?= e(app_url('pages/mutuelles.php')) ?>">Retour</a><button class="btn btn-primary" type="submit">Enregistrer</button></div></form>
<?php if(has_role(['admin','patron'])):?>
<form class="card" method="post" action="<?= e(app_url('actions/mutual_request_delete.php')) ?>" data-confirm="Supprimer cette demande mutuelle et ses relances ? Le dossier client sera conservé.">
<?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$request['id'] ?>">
<div class="card-header"><div><h2>Supprimer ce suivi mutuelle</h2><p>À utiliser pour une demande créée par erreur. Cette action ne supprime pas le dossier client.</p></div></div>
<button class="btn btn-danger" type="submit">Supprimer la demande mutuelle</button>
</form>
<?php endif;?>
<?php require dirname(__DIR__) . '/includes/footer.php';?>
