<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php';redirect_if_not_logged_in();
$status=trim((string)($_GET['status']??''));$allowed=['a_preparer','envoyee','confirmee','en_fabrication','expediee','recue','montage','prete','incident','annulee'];$where='1=1';$params=[];if(in_array($status,$allowed,true)){$where='go.status=?';$params[]=$status;}
$stmt=db()->prepare('SELECT go.*,d.client_id,d.folder_status,CONCAT(c.first_name," ",c.last_name) AS client_name FROM glass_orders go JOIN dossiers d ON d.id=go.dossier_id JOIN clients c ON c.id=d.client_id WHERE '.$where.' ORDER BY FIELD(go.status,"incident","a_preparer","envoyee","confirmee","en_fabrication","expediee","recue","montage","prete","annulee"),go.expected_at');$stmt->execute($params);$orders=$stmt->fetchAll();
$pageTitle='Commandes Ophtalmic';require dirname(__DIR__) . '/includes/header.php';
?>
<section class="page-actions"><div class="copy"><h2>Pilotage verrier</h2><p>Préparez les valeurs à reporter, ouvrez E-Space puis recopiez ici la référence et le statut. Aucune commande n’est envoyée automatiquement.</p></div><a class="btn btn-primary" target="_blank" rel="noopener noreferrer" href="<?= e(app_config()['suppliers']['ophtalmic_portal_url']) ?>">Ouvrir Ophtalmic E-Space ↗</a></section>
<nav class="filter-tabs"><a href="?">Toutes</a><?php foreach(['a_preparer','envoyee','en_fabrication','expediee','recue','montage','prete','incident'] as $item):?><a class="<?= $status===$item?'active':'' ?>" href="?status=<?= e($item) ?>"><?= e(status_label($item)) ?></a><?php endforeach;?></nav>
<section class="card table-card"><div class="table-wrap"><table><thead><tr><th>Dossier</th><th>Client</th><th>Correction</th><th>Produit</th><th>Référence</th><th>Prévue</th><th>Statut</th><th>Actions</th></tr></thead><tbody>
<?php foreach($orders as $order):?><tr class="<?= $order['status']==='incident'?'row-warning':'' ?>"><td><a class="cell-title" href="<?= e(app_url('pages/dossier_view.php?id='.$order['dossier_id'])) ?>"><?= e(dossier_number((int)$order['dossier_id'])) ?></a></td><td><?= e($order['client_name']) ?></td><td><span class="cell-title">OD <?= e(($order['lens_right_sphere']??'—').' / '.($order['lens_right_cylinder']??'—').' × '.($order['lens_right_axis']??'—')) ?></span><span class="cell-subtitle">OG <?= e(($order['lens_left_sphere']??'—').' / '.($order['lens_left_cylinder']??'—').' × '.($order['lens_left_axis']??'—')) ?></span></td><td><?= e($order['lens_product']?:'—') ?><span class="cell-subtitle"><?= e(trim(($order['lens_index']?:'').' '.($order['treatment']?:''))) ?></span></td><td><?= e($order['order_reference']?:'À reporter') ?></td><td><?= e(format_date($order['expected_at'],true)) ?></td><td><?= status_badge($order['status']) ?></td><td><div class="inline-actions"><a class="btn btn-small btn-outline" href="<?= e(app_url('pages/dossier_edit.php?id='.$order['dossier_id'])) ?>">Modifier</a><?php foreach(['envoyee'=>'Envoyée','recue'=>'Reçue','montage'=>'Montage','prete'=>'Prête'] as $next=>$label):?><form method="post" action="<?= e(app_url('actions/ophtalmic_status.php')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><input type="hidden" name="status" value="<?= e($next) ?>"><button class="btn btn-small <?= $next==='prete'?'btn-success':'btn-outline' ?>" type="submit"><?= e($label) ?></button></form><?php endforeach;?></div></td></tr><?php endforeach;?>
<?php if(!$orders):?><tr><td colspan="8" class="empty-state">Aucune commande pour ce filtre.</td></tr><?php endif;?></tbody></table></div></section>
<?php require dirname(__DIR__) . '/includes/footer.php';?>
