<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php';redirect_if_not_logged_in();
$q=mb_substr(trim((string)($_GET['q']??'')),0,100);$clients=$folders=$tasks=$payments=[];
if(mb_strlen($q)>=2){$like='%'.$q.'%';$stmt=db()->prepare('SELECT id,fiche_number,first_name,last_name,phone,email FROM clients WHERE first_name LIKE ? OR last_name LIKE ? OR fiche_number LIKE ? OR phone LIKE ? OR email LIKE ? ORDER BY last_name,first_name LIMIT 25');$stmt->execute(array_fill(0,5,$like));$clients=$stmt->fetchAll();
$numeric=preg_replace('/\D/','',$q);$stmt=db()->prepare('SELECT d.id,d.folder_status,d.next_action,c.first_name,c.last_name FROM dossiers d JOIN clients c ON c.id=d.client_id WHERE CAST(d.id AS CHAR) LIKE ? OR d.pec_reference LIKE ? OR d.next_action LIKE ? OR c.first_name LIKE ? OR c.last_name LIKE ? ORDER BY d.updated_at DESC LIMIT 25');$stmt->execute([$numeric!==''?'%'.$numeric.'%':$like,$like,$like,$like,$like]);$folders=$stmt->fetchAll();
$stmt=db()->prepare('SELECT t.*,c.first_name,c.last_name FROM tasks t LEFT JOIN clients c ON c.id=t.client_id WHERE t.title LIKE ? OR t.description LIKE ? ORDER BY t.due_at LIMIT 25');$stmt->execute([$like,$like]);$tasks=$stmt->fetchAll();
$stmt=db()->prepare('SELECT p.*,d.client_id,c.first_name,c.last_name FROM payments p JOIN dossiers d ON d.id=p.dossier_id JOIN clients c ON c.id=d.client_id WHERE CAST(p.id AS CHAR) LIKE ? OR CAST(p.dossier_id AS CHAR) LIKE ? OR c.first_name LIKE ? OR c.last_name LIKE ? ORDER BY p.updated_at DESC LIMIT 25');$stmt->execute([$like,$like,$like,$like]);$payments=$stmt->fetchAll();}
$pageTitle='Recherche globale';require dirname(__DIR__) . '/includes/header.php';
?>
<form class="filters" method="get" style="grid-template-columns:minmax(300px,1fr) auto"><div class="search-input"><input type="search" name="q" value="<?= e($q) ?>" placeholder="Client, fiche, dossier, tâche, paiement…" autofocus></div><button class="btn btn-primary" type="submit">Rechercher</button></form>
<?php if($q!==''&&mb_strlen($q)<2):?><div class="alert alert-warning">Saisissez au moins 2 caractères.</div><?php endif;?>
<?php if(mb_strlen($q)>=2):?>
<section class="card table-card"><div class="card-header"><h2>Clients (<?= count($clients) ?>)</h2></div><div class="table-wrap"><table><tbody><?php foreach($clients as $row):?><tr><td><a class="cell-title" href="<?= e(app_url('pages/client_view.php?id='.$row['id'])) ?>"><?= e($row['last_name'].' '.$row['first_name']) ?></a><span class="cell-subtitle"><?= e(($row['fiche_number']?:'sans n°').' · '.($row['phone']?:'sans téléphone')) ?></span></td></tr><?php endforeach;?><?php if(!$clients):?><tr><td class="empty-state">Aucun client.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card table-card"><div class="card-header"><h2>Dossiers (<?= count($folders) ?>)</h2></div><div class="table-wrap"><table><tbody><?php foreach($folders as $row):?><tr><td><a class="cell-title" href="<?= e(app_url('pages/dossier_view.php?id='.$row['id'])) ?>"><?= e(dossier_number((int)$row['id']).' · '.$row['last_name'].' '.$row['first_name']) ?></a><span class="cell-subtitle"><?= e(status_label($row['folder_status']).' · '.($row['next_action']?:'sans prochaine action')) ?></span></td></tr><?php endforeach;?><?php if(!$folders):?><tr><td class="empty-state">Aucun dossier.</td></tr><?php endif;?></tbody></table></div></section>
<div class="content-grid"><section class="card table-card"><div class="card-header"><h2>Tâches (<?= count($tasks) ?>)</h2></div><div class="table-wrap"><table><tbody><?php foreach($tasks as $row):?><tr><td><?= $row['dossier_id']?'<a class="cell-title" href="'.e(app_url('pages/dossier_view.php?id='.$row['dossier_id'])).'">'.e($row['title']).'</a>':e($row['title']) ?><span class="cell-subtitle"><?= e(format_date($row['due_at'],true)) ?> · <?= status_badge($row['status']) ?></span></td></tr><?php endforeach;?><?php if(!$tasks):?><tr><td class="empty-state">Aucune tâche.</td></tr><?php endif;?></tbody></table></div></section><section class="card table-card"><div class="card-header"><h2>Paiements (<?= count($payments) ?>)</h2></div><div class="table-wrap"><table><tbody><?php foreach($payments as $row):?><tr><td><a class="cell-title" href="<?= e(app_url('pages/dossier_view.php?id='.$row['dossier_id'])) ?>"><?= e(dossier_number((int)$row['dossier_id']).' · '.status_label($row['payer'])) ?></a><span class="cell-subtitle"><?= e($row['last_name'].' '.$row['first_name'].' · '.format_euros($row['paid_amount']).' / '.format_euros($row['expected_amount'])) ?></span></td></tr><?php endforeach;?><?php if(!$payments):?><tr><td class="empty-state">Aucun paiement.</td></tr><?php endif;?></tbody></table></div></section></div>
<?php endif;?>
<?php require dirname(__DIR__) . '/includes/footer.php';?>

